name: jnigen_benchmark
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0-242.0.dev

dependencies:
  benchmark_harness: ^2.2.2
  jni:
    path: ../native/pkgs/jni

dev_dependencies:
  jnigen: ^0.8.0
  lints: ^3.0.0
  test: ^1.24.0
